#!/usr/bin/env node
/**
 * The package's transpile step.
 *
 * Three artifacts, from TypeScript sources:
 *
 * - `lib/index.js` — the Host half. ESM, `platform: node`; every bare specifier
 *   stays external so the plugin resolves services through the running
 *   installation and never ships its own copy of a DSH package.
 * - `lib/client.js` — the browser half, in the DSH closure-factory form:
 *   `window.__ModuleLoader__.load({ id, factory })` with the injected `require`
 *   resolving module-table entries. Only the shell's baseline plus anything the
 *   manifest requests under `dsh.client.external` stays external; every other
 *   dependency (the pure `dsh-util-workspace-path` fold, for instance) is inlined.
 * - `lib/types/**` — declarations for both faces.
 *
 * A purity gate then re-reads the emitted browser bundle and refuses any
 * `require()` the module table could not answer, which is the build-time mirror
 * of the rule the DSH client-bundle preset enforces.
 */
import { spawnSync } from 'node:child_process'
import { readFile, rm } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))

/**
 * The module specifiers the shell shares into its frozen module table
 * (`PLATFORM_MODULES` in `packages/client/web/src/platform.ts`). A dynamic
 * browser bundle may require exactly these without declaring them.
 */
const PLATFORM_MODULES = [
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
]

const declaration = manifest.dsh?.client ?? {}
const requested = Array.isArray(declaration.external) ? declaration.external : []
const allowedExternals = new Set([...PLATFORM_MODULES, ...requested])
const pluginId = manifest.name

if (typeof pluginId !== 'string' || pluginId === '') {
  throw new Error('build: package.json has no name')
}

await rm(resolve(root, 'lib'), { recursive: true, force: true })

// ── the Host half ────────────────────────────────────────────────────────────
await build({
  absWorkingDir: root,
  entryPoints: ['src/index.ts'],
  outfile: 'lib/index.js',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  packages: 'external',
  sourcemap: true,
  logLevel: 'warning',
  banner: { js: '// Generated by scripts/build.mjs from src/index.ts — do not edit.' },
})

// ── the browser half ─────────────────────────────────────────────────────────
await build({
  absWorkingDir: root,
  entryPoints: ['src/client/index.ts'],
  outfile: 'lib/client.js',
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  external: [...allowedExternals],
  sourcemap: true,
  logLevel: 'warning',
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production'),
    'import.meta.env.MODE': JSON.stringify(process.env.NODE_ENV ?? 'production'),
    'import.meta.env': JSON.stringify({ MODE: process.env.NODE_ENV ?? 'production' }),
  },
  // The DSH closure-factory handoff: `banner` opens the factory and declares the
  // CommonJS bindings esbuild's `format: 'cjs'` output writes to, `footer` closes
  // both and returns what the module table materializes.
  banner: {
    js: 'window.__ModuleLoader__.load({ id: ' + JSON.stringify(pluginId) + ', factory: (require) => {'
      + ' var module = { exports: {} }; var exports = module.exports;',
  },
  footer: { js: 'return module.exports; } });' },
})

// ── the module-graph gate ────────────────────────────────────────────────────
const clientSource = await readFile(resolve(root, 'lib/client.js'), 'utf8')
const asked = new Set()
for (const match of clientSource.matchAll(/\brequire\(\s*(["'])([^"']+)\1\s*\)/gu)) {
  asked.add(match[2])
}
const undeclared = [...asked].filter(specifier => !allowedExternals.has(specifier))
if (undeclared.length > 0) {
  throw new Error(
    `build: lib/client.js requires ${undeclared.map(name => JSON.stringify(name)).join(', ')}, `
    + 'which is neither a platform module nor declared in dsh.client.external — '
    + 'a require() the module table cannot answer is a guaranteed runtime throw',
  )
}
process.stdout.write(`build: lib/client.js externals ok (${[...asked].sort().join(', ')})\n`)

// ── test-only entry points ───────────────────────────────────────────────────
// The pure folds stay internal to the two shipped artifacts, so the suite needs
// its own entry points to reach them. `lib/testing/` is outside the manifest's
// `files` list and is never published.
await build({
  absWorkingDir: root,
  entryPoints: {
    'host-git': 'src/host/git.ts',
    'client-changes': 'src/client/changes.ts',
    'client-levels': 'src/client/levels.ts',
    'client-diff': 'src/client/diff.ts',
    'client-image': 'src/client/image.ts',
    'client-tokrate': 'src/client/tokrate.ts',
    'client-liverate': 'src/client/liverate.ts',
    'client-notify': 'src/client/notify.ts',
    'client-pillrate': 'src/client/pillrate.ts',
    'client-route': 'src/client/route.ts',
    'client-closeall': 'src/client/closeall.ts',
    'client-autohistory': 'src/client/autohistory.ts',
    'client-expandall': 'src/client/expandall.ts',
    'client-drafts': 'src/client/drafts.ts',
    'client-draftwatch': 'src/client/draftwatch.ts',
    'client-sessions': 'src/client/sessions.ts',
  },
  outdir: 'lib/testing',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  packages: 'external',
  sourcemap: false,
  logLevel: 'warning',
  banner: { js: '// Test-only entry points, built by scripts/build.mjs; not published.' },
})

// ── declarations ─────────────────────────────────────────────────────────────
const tsc = spawnSync(resolve(root, 'node_modules/.bin/tsc'), ['-p', 'tsconfig.build.json'], {
  cwd: root,
  stdio: 'inherit',
})
if (tsc.status !== 0) {
  process.stderr.write('build: declaration emit failed\n')
  process.exit(tsc.status ?? 1)
}

process.stdout.write('build: wrote lib/index.js, lib/client.js, lib/types/**\n')
